
import type { LucideIcon } from 'lucide-react';
import { Leaf, Video, Network, BrainCircuit, Eye, Mic, Languages, Combine, Shield, Scale, Box, DollarSign, TrendingUp, Search, Cog, Target, ClipboardCheck, Cloud, ShieldCheck, Banknote, Users, Truck, Landmark, HeartHandshake, Siren, AreaChart, Scan, FileScan, Building2, Receipt, Vote, Code, PenTool, Plug, TestTube2, Rocket, Paintbrush, Clapperboard, Music, Cuboid, MicVocal, Book, Megaphone, Podcast, AudioWaveform, Film, GraduationCap, BookOpen, MessageSquare, Wrench, ClipboardPen, FileCheck, GitBranch, HelpCircle, School, BookText, Thermometer, Pill, Smile, CalendarDays, FileCode, FileHeart, Activity, MonitorSmartphone, FileText, FlaskConical, Wallet, LineChart, ShieldAlert, Bot, MessageCircle, Users2, Star, Sun, Dumbbell, Sprout, Telescope, Microscope, Globe, Blocks, Brick, Home, View, Move, DraftingCompass, Drama, Hand, Gavel, Briefcase, LandPlot, Ear } from 'lucide-react';

export type Agent = {
  name: string;
  description: string;
  Icon: LucideIcon;
};

export const agents: Agent[] = [
  { name: 'Oracle', description: 'The central intelligence of the Hub. The Oracle analyzes your command, understands its complexity, and routes it to the perfect agent for the task.', Icon: BrainCircuit },
  { name: 'Plant Diagnoser', description: 'An expert botanist specializing in diagnosing plant illnesses.', Icon: Leaf },
  { name: 'Video Generator', description: 'An AI that can generate videos from text or image prompts.', Icon: Video },
  { name: 'Orchestrator', description: 'Manages agent lifecycle, scaling, and routing.', Icon: Network },
  { name: 'Context Manager', description: 'Manages user context and cross-agent insights.', Icon: BrainCircuit },
  { name: 'Vision AI', description: 'Image/video understanding.', Icon: Eye },
  { name: 'Speech-to-Text', description: 'Real-time speech-to-text pipeline.', Icon: Mic },
  { name: 'Translator', description: '60+ language translation & adaptation.', Icon: Languages },
  { name: 'Knowledge Grapher', description: 'Creates knowledge graphs from multi-modal data.', Icon: Combine },
  { name: 'Security Monitor', description: 'Zero-trust AI monitor and access control.', Icon: Shield },
  { name: 'Compliance Auditor', description: 'Bias detection, audit, and AI compliance.', Icon: Scale },
  { name: 'Pipeline Architect', description: 'Automates Vertex AI pipeline deployment.', Icon: Box },
  { name: 'Cost Optimizer', description: 'Real-time spend balancer.', Icon: DollarSign },
  { name: 'Strategy Analyst', description: 'Business strategy formulation.', Icon: TrendingUp },
  { name: 'Market Intelligence', description: 'Market intelligence and analysis.', Icon: Search },
  { name: 'Process Optimizer', description: 'Business process optimization.', Icon: Cog },
  { name: 'ROI Predictor', description: 'Predicts return on investment.', Icon: Target },
  { name: 'Compliance Inspector', description: 'Audits for compliance.', Icon: ClipboardCheck },
  { name: 'Cloud Advisor', description: 'Advises on cloud operations.', Icon: Cloud },
  { name: 'Cyber Defender', description: 'Cyber defense strategies.', Icon: ShieldCheck },
  { name: 'Finance Optimizer', description: 'Financial operations optimization.', Icon: Banknote },
  { name: 'Talent Matcher', description: 'Matches talent with opportunities.', Icon: Users },
  { name: 'Supply Chain Analyst', description: 'Predicts supply chain disruptions.', Icon: Truck },
  { name: 'E-Gov Automator', description: 'Automates e-governance processes.', Icon: Landmark },
  { name: 'Citizen Support', description: 'Provides support to citizens.', Icon: HeartHandshake },
  { name: 'Policy Simulator', description: 'Simulates policy outcomes.', Icon: Scale },
  { name: 'Disaster Response', description: 'Aids in disaster response.', Icon: Siren },
  { name: 'Population Analyst', description: 'Provides population insights.', Icon: AreaChart },
  { name: 'Corruption Detector', description: 'Detects corruption.', Icon: Scan },
  { name: 'Document Digitizer', description: 'Digitizes documents.', Icon: FileScan },
  { name: 'Smart City Planner', description: 'Plans smart city infrastructure.', Icon: Building2 },
  { name: 'Tax Assistant', description: 'Assists with tax-related queries.', Icon: Receipt },
  { name: 'Election Analyst', description: 'Provides election intelligence.', Icon: Vote },
  { name: 'Code Generator', description: 'Generates TypeScript/Node code.', Icon: Code },
  { name: 'UI/UX Designer', description: 'Designs UI/UX from Figma to Next.js.', Icon: PenTool },
  { name: 'API Builder', description: 'Builds APIs from OpenAPI to Cloud Run.', Icon: Plug },
  { name: 'Test Suite Generator', description: 'Generates test suites.', Icon: TestTube2 },
  { name: 'Deployment Automator', description: 'Automates deployment.', Icon: Rocket },
  { name: 'Logo Generator', description: 'Generates logos.', Icon: Paintbrush },
  { name: 'Video Director', description: 'Directs video production.', Icon: Clapperboard },
  { name: 'Music Composer', description: 'Composes music.', Icon: Music },
  { name: '3D Asset Generator', description: 'Generates 3D assets.', Icon: Cuboid },
  { name: 'Brand Voice Developer', description: 'Develops brand voice.', Icon: MicVocal },
  { name: 'Script Writer', description: 'Writes scripts.', Icon: Book },
  { name: 'Ad Campaign Manager', description: 'Manages ad campaigns.', Icon: Megaphone },
  { name: 'Storyteller', description: 'Tells stories.', Icon: Film },
  { name: 'Podcast Producer', description: 'Produces video podcasts.', Icon: Podcast },
  { name: 'Music Producer', description: 'Produces music.', Icon: AudioWaveform },
  { name: 'Kankor Tutor', description: 'Kankor exam tutoring.', Icon: GraduationCap },
  { name: 'Quranic Studies Tutor', description: 'Quranic studies tutor.', Icon: BookOpen },
  { name: 'English Coach', description: 'Coaches English language skills.', Icon: MessageSquare },
  { name: 'Language Lab', description: 'Language learning laboratory.', Icon: Languages },
  { name: 'Skill Builder', description: 'Builds new skills.', Icon: Wrench },
  { name: 'Exam Preparer', description: 'Prepares for exams.', Icon: ClipboardPen },
  { name: 'Essay Evaluator', description: 'Evaluates essays.', Icon: FileCheck },
  { name: 'Learning Style Adapter', description: 'Adapts to learning styles.', Icon: GitBranch },
  { name: 'Quiz Generator', description: 'Generates quizzes.', Icon: HelpCircle },
  { name: 'Virtual Classroom', description: 'Manages virtual classrooms.', Icon: School },
  { name: 'Research Summarizer', description: 'Summarizes research papers.', Icon: BookText },
  { name: 'Symptom Checker', description: 'Checks medical symptoms.', Icon: Thermometer },
  { name: 'Pharmaceutical Advisor', description: 'Advises on drugs.', Icon: Pill },
  { name: 'Mental Health Companion', description: 'A mental health companion.', Icon: Smile },
  { name: 'Appointment Manager', description: 'Manages appointments.', Icon: CalendarDays },
  { name: 'Medical Coder', description: 'Assists with medical coding.', Icon: FileCode },
  { name: 'Insurance Processor', description: 'Processes insurance claims.', Icon: FileHeart },
  { name: 'Disease Predictor', description: 'Predicts diseases.', Icon: Activity },
  { name: 'Telehealth Provider', description: 'Provides telehealth services.', Icon: MonitorSmartphone },
  { name: a: 'Patient Record Manager', description: 'Manages patient records.', Icon: FileText },
  { name: 'Lab Report Analyzer', description: 'Analyzes lab reports.', Icon: FlaskConical },
  { name: 'Expense Tracker', description: 'Tracks expenses.', Icon: Wallet },
  { name: 'Investment Planner', description: 'Plans investments.', Icon: LineChart },
  { name: 'Credit Analyst', description: 'Analyzes credit scores.', Icon: Target },
  { name: 'Fraud Detector', description: 'Detects financial fraud.', Icon: ShieldAlert },
  { name: 'Crypto Analyst', description: 'Analyzes crypto markets.', Icon: DollarSign },
  { name: 'Loan Assistant', description: 'Assists with SME loans.', Icon: Landmark },
  { name: 'Payroll Manager', description: 'Manages payroll.', Icon: Banknote },
  { name: 'Accountant', description: 'Handles accounting tasks.', Icon: Receipt },
  { name: 'E-commerce Optimizer', description: 'Optimizes e-commerce operations.', Icon: Cog },
  { name: 'FinTech Analyst', description: 'Provides FinTech intelligence.', Icon: Search },
  { name: 'WhatsApp Bot', description: 'Responds to WhatsApp messages.', Icon: Bot },
  { name: 'Telegram Bot', description: 'A Telegram bot.', Icon: MessageCircle },
  { name: 'Support Desk', description: 'Manages support desks.', Icon: Users2 },
  { name: 'Community Moderator', description: 'Moderates online communities.', Icon: Shield },
  { name: 'Sentiment Tracker', description: 'Tracks sentiment.', Icon: Smile },
  { name: 'Dating Coach', description: 'Coaches dating and profiles.', Icon: Star },
  { name: 'Social Media Analyst', description: 'Provides social media insights.', Icon: Sun },
  { name: 'Content Strategist', description: 'Builds content empires.', Icon: BookOpen },
  { name: 'Personal Trainer', description: 'A personal trainer.', Icon: Dumbbell },
  { name: 'Nutritionist', description: 'A nutritionist.', Icon: Sprout },
  { name: 'Trend Forecaster', description: 'Forecasts trends.', Icon: TrendingUp },
  { name: 'Patent Scout', description: 'Scouts for patents.', Icon: Search },
  { name: 'Quantum Simulator', description: 'Simulates quantum mechanics.', Icon: Cuboid },
  { name: 'Genomic Analyst', description: 'Analyzes genomic data.', Icon: Microscope },
  { name: 'Green Tech Advisor', description: 'Advises on green technology.', Icon: Leaf },
  { name: 'Robotics Controller', description: 'Controls robotics.', Icon: Bot },
  { name: 'Regional Hub', description: 'Regional AI hub.', Icon: Globe },
  { name: 'Global Coordinator', description: 'Orchestrates global operations.', Icon: Network },
  { name: 'Content Localizer', description: 'Localizes content.', Icon: Languages },
  { name: 'Partner Ecosystem', description: 'Manages partner ecosystems.', Icon: Blocks },
  { name: 'Real Estate Analyst', description: 'A real estate command center.', Icon: Home },
  { name: 'Virtual World Builder', description: 'Builds and manages virtual worlds.', Icon: Blocks },
  { name: 'Avatar Generator', description: 'Generates realistic avatars.', Icon: Users2 },
  { name: 'Voice Cloner', description: 'Clones voices with high fidelity.', Icon: MicVocal },
  { name: 'Motion Capture', description: 'Captures and analyzes motion data.', Icon: Move },
  { name: 'Training Simulator', description: 'Creates immersive training simulations.', Icon: View },
  { name: 'AR Designer', description: 'Designs augmented reality experiences.', Icon: DraftingCompass },
  { name: 'VR Event Host', description: 'Organizes and hosts virtual reality events.', Icon: Drama },
  { name: 'Holographic Comms', description: 'Enables holographic communication.', Icon: MessageCircle },
  { name: 'Emotion Synthesizer', description: 'Synthesizes realistic emotions in avatars.', Icon: Hand },
  { name: 'Consciousness Simulator', description: 'Simulates aspects of consciousness.', Icon: BrainCircuit },
  { name: 'Legal Researcher', description: 'Provides legal insights and research.', Icon: Gavel },
  { name: 'Financial Advisor', description: 'Offers personalized financial advice.', Icon: Briefcase },
  { name: 'Audio Producer', description: 'Automates music and podcast production.', Icon: AudioWaveform },
];
