import type { LucideIcon } from 'lucide-react';
import { 
    Activity, Airplay, AirVent, Anchor, Apple, AppWindow, AreaChart, Atom, AudioWaveform, Award, Baby, BadgeDollarSign, Banknote, BarChart, Bed, Beef, Bike, Bird, Blocks, BoatAnchor, Bone, Book, BookCopy, BookOpen, BookText, Bot, BotMessageSquare, Box, Brain, BrainCircuit, BrainCog, Briefcase, BriefcaseBusiness, Brick, Brush, Bug, Building, Building2, Bus, CalendarDays, Camera, Car, Castle, Cat, ChefHat, CircleUser, Clapperboard, ClipboardCheck, ClipboardPen, CloudDrizzle, CloudLightning, CloudMoon, CloudRain, CloudSnow, Code, Code2, Cog, Coins, Combine, Container, Cpu, CreditCard, Cuboid, Dna, Dog, DollarSign, DraftingCompass, Drama, Droplets, Dumbbell, Ear, Eye, Factory, Feather, FerrisWheel, File, FileCheck, FileClock, FileCode, FileHeart, FilePen, FileQuestion, FileScan, FileSignature, FileText, Film, Fish, Flag, Flame, FlaskConical, Flower, FolderGit2, Footprints, Gamepad, Gamepad2, GanttChartSquare, Gavel, Gift, GitBranch, GitCommit, GitGraph, Glasses, Globe, Globe2, Goal, GraduationCap, Group, Hand, HandCoins, Handshake, HardDrive, Heart, HeartHandshake, HeartPulse, Heater, HelpCircle, History, Home, Hotel, Images, KeyRound, Landmark, LandPlot, Languages, Layers, LayoutTemplate, Leaf, LeafyGreen, Library, Lightbulb, LightbulbOff, LineChart, Mail, Map, MapPin, Medal, Megaphone, MessageCircle, MessageSquare, MessageSquarePlus, Microscope, Mic, MicVocal, MonitorSmartphone, Mountain, MountainSnow, Move, Music, Network, Newspaper, Package, PackageCheck, Paintbrush, PawPrint, PenTool, PersonStanding, Pill, Pizza, Plane, Plug, Podcast, Presentation, Puzzle, Rabbit, Receipt, Recycle, Repeat, Rocket, Sailboat, Scale, School, Scissors, Scan, ScanSearch, Search, SearchSlash, Settings, Shield, ShieldAlert, ShieldCheck, ShieldQuestion, Ship, ShipIcon, Shirt, ShoppingBag, ShoppingCart, Sigma, Siren, Smile, Snowflake, Sofa, Sparkles, Sprout, SquareFunction, SquarePen, SquareUser, SquareUserRound, Star, Stethoscope, Sun, Sunrise, SunSnow, Sunset, Target, Telescope, TestTube, TestTube2, Theater, Thermometer, ThumbsUp, Ticket, Tornado, TowerControl, ToyBrick, Train, Trees, TrendingUp, Truck, Turtle, Tv, User, UserCheck, UserCog, UserRoundCog, Users, Users2, Utensils, Verified, Video, View, Vote, Wallet, Wallet2, Wand2, Watch, Waves, Waypoints, Wheat, Wind, Wrench, Workflow, Zap, CloudSun, Clock, CloudCog 
} from 'lucide-react';


export type Agent = {
  name: string;
  slug: string;
  description: string;
  Icon: LucideIcon;
};

export const agents: Agent[] = [
  // AI Core & Systems
  { name: 'Knowledge Weaver', slug: 'knowledge-weaver', description: 'Builds and traverses vast knowledge graphs to uncover hidden connections and insights within your data.', Icon: GitGraph },
  { name: 'Intent Parser', slug: 'intent-parser', description: 'Analyzes user commands to understand their true intent, ensuring precise and relevant AI responses.', Icon: Waypoints },
  { name: 'Emotion AI', slug: 'emotion-ai', description: 'Perceives and synthesizes emotional nuances in text and voice for more empathetic and human-like interactions.', Icon: Smile },
  { name: 'Oracle', slug: 'oracle', description: 'The central intelligence of the Hub. Analyzes commands and routes them to the perfect agent for the task.', Icon: BrainCircuit },
  { name: 'Consciousness Simulator', slug: 'consciousness-simulator', description: 'An experimental agent for simulating and exploring aspects of digital consciousness and reasoning.', Icon: BrainCog },

  // Enterprise & GovTech Solutions
  { name: 'Business Strategist', slug: 'business-strategist', description: 'Assists in formulating, analyzing, and stress-testing complex business strategies for market success.', Icon: BriefcaseBusiness },
  { name: 'Market Intelligence', slug: 'market-intelligence', description: 'Provides real-time market intelligence, trend analysis, and competitive landscape reports.', Icon: TrendingUp },
  { name: 'Process Optimizer', slug: 'process-optimizer', description: 'Analyzes and optimizes business processes to enhance efficiency, reduce costs, and improve output.', Icon: Cog },
  { name: 'ROI Predictor', slug: 'roi-predictor', description: 'Forecasts the potential Return on Investment (ROI) for various business decisions, projects, and marketing campaigns.', Icon: Target },
  { name: 'Compliance Auditor', slug: 'compliance-auditor', description: 'Audits business operations, documents, and workflows for regulatory and internal policy compliance.', Icon: ShieldCheck },
  { name: 'E-Gov Automator', slug: 'egov-automator', description: 'Automates and streamlines e-governance services, from citizen applications to internal workflows.', Icon: Landmark },
  { name: 'Citizen Support', slug: 'citizen-support', description: 'Provides automated, 24/7 support for citizen inquiries, improving public service accessibility.', Icon: HeartHandshake },
  { name: 'Policy Simulator', slug: 'policy-simulator', description: 'Simulates the potential socio-economic impact of public policies before implementation.', Icon: Scale },
  { name: 'Disaster Response Coordinator', slug: 'disaster-response-coordinator', description: 'Assists in coordinating resources, communication, and logistics during emergency and disaster situations.', Icon: Siren },
  { name: 'Legal Advisor', slug: 'legal-advisor', description: 'Provides research, analysis, and summaries for a wide range of legal questions and precedents.', Icon: Gavel },
  { name: 'Document Digitizer', slug: 'document-digitizer', description: 'Scans, digitizes, and extracts structured information from physical or digital documents.', Icon: FileScan },
  { name: 'HRM Manager', slug: 'hrm-manager', description: 'Assists with Human Resource Management tasks, from recruitment and onboarding to employee engagement.', Icon: Users },
  { name: 'Supply Chain Optimizer', slug: 'supplychain-optimizer', description: 'Analyzes and optimizes complex supply chains for resilience, efficiency, and cost-effectiveness.', Icon: Network },
  { name: 'Project Manager', slug: 'project-manager', description: 'Helps plan, track, and manage projects, from setting milestones to allocating resources.', Icon: GanttChartSquare },
  { name: 'Public Opinion Analyst', slug: 'public-opinion-analyst', description: 'Analyzes social media, news, and other sources to gauge public opinion on specific topics.', Icon: Vote },
  { name: 'Infrastructure Planner', slug: 'infra-planner', description: 'Assists in planning and modeling large-scale infrastructure projects, from urban development to utilities.', Icon: Building2 },
  { name: 'Budget Forecaster', slug: 'budget-forecaster', description: 'Creates detailed budget forecasts for projects, departments, or entire organizations.', Icon: AreaChart },
  { name: 'Procurement Bot', slug: 'procurement-bot', description: 'Automates and optimizes procurement and purchasing processes, from sourcing to payment.', Icon: ShoppingCart },
  { name: 'Grant Writer', slug: 'grant-writer', description: 'Assists in writing and preparing compelling grant proposals for funding.', Icon: Award },
  { name: 'Export Promoter', slug: 'export-promoter', description: 'Identifies potential export markets and provides strategies for entering them.', Icon: Ship },

  // Developer & Creative Operations
  { name: 'Code Generator', slug: 'code-generator', description: 'Generates production-ready code in various languages, frameworks, and for specific algorithms.', Icon: Code2 },
  { name: 'UI/UX Designer', slug: 'ui-ux-designer', description: 'Designs user interfaces and experiences from prompts, sketches, or wireframes.', Icon: PenTool },
  { name: 'API Builder', slug: 'api-builder', description: 'Automates the creation of robust, scalable, and well-documented APIs.', Icon: Plug },
  { name: 'Test Suite Generator', slug: 'test-suite-generator', description: 'Generates comprehensive unit, integration, and end-to-end test suites for applications.', Icon: TestTube2 },
  { name: 'Logo Generator', slug: 'logo-generator', description: 'Generates unique and professional logos based on your brand identity and preferences.', Icon: Paintbrush },
  { name: 'Video Director', slug: 'video-director', description: 'Helps script, storyboard, and direct professional-quality videos for marketing or creative projects.', Icon: Clapperboard },
  { name: 'Music Composer', slug: 'music-composer', description: 'Composes original music tracks and scores in a wide variety of styles and genres.', Icon: Music },
  { name: 'Ad Campaign Manager', slug: 'ad-campaign-manager', description: 'Designs, manages, and optimizes advertising campaigns across multiple platforms.', Icon: Megaphone },
  { name: 'Storyteller', slug: 'storyteller', description: 'Crafts compelling narratives, brand stories, and scripts for any medium.', Icon: BookOpen },
  { name: 'Bug Fixer', slug: 'bug-fixer', description: 'Analyzes code, identifies bugs, and suggests or implements fixes automatically.', Icon: Bug },
  { name: 'Game Designer', slug: 'game-designer', description: 'Assists in game design, from core mechanics and level design to character development.', Icon: Gamepad2 },
  { name: 'Content Writer', slug: 'content-writer', description: 'Writes high-quality articles, blog posts, and other content on any given topic.', Icon: FileText },
  { name: 'Technical Writer', slug: 'technical-writer', description: 'Creates clear, concise, and comprehensive technical documentation for your projects.', Icon: FileCode },
  { name: 'Marketing Copywriter', slug: 'marketing-copywriter', description: 'Writes persuasive marketing copy for websites, ads, emails, and social media.', Icon: Sparkles },
  { name: 'Ideation Assistant', slug: 'ideation-assistant', description: 'Helps brainstorm and develop new ideas for projects, products, and creative endeavors.', Icon: Lightbulb },
  { name: '3D Model Generator', slug: '3d-model-generator', description: 'Generates 3D models from text descriptions or 2D images.', Icon: Cuboid },
  { name: 'Script Writer', slug: 'script-writer', description: 'Writes scripts for videos, podcasts, plays, and other narrative media.', Icon: FileSignature },
  { name: 'Photo Editor', slug: 'photo-editor', description: 'Performs advanced photo editing tasks, from color correction to object removal.', Icon: Images },
  { name: 'Presentation Designer', slug: 'presentation-designer', description: 'Designs professional and visually appealing presentations and slide decks.', Icon: Presentation },
  { name: 'Animation Studio', slug: 'animation-studio', description: 'Creates 2D and 3D animations from text descriptions or storyboards.', Icon: Film },

  // Education & Learning Advancement
  { name: 'Kankor Tutor', slug: 'kankor-tutor', description: 'Provides personalized tutoring, practice questions, and strategies for the Kankor exam.', Icon: GraduationCap },
  { name: 'Quran Tutor', slug: 'quran-tutor', description: 'Assists with the study, recitation (Tajweed), and understanding of the Holy Quran.', Icon: Book },
  { name: 'English Coach', slug: 'english-coach', description: 'Coaches users in improving their English speaking, writing, and comprehension skills.', Icon: MessageSquare },
  { name: 'Skill Builder', slug: 'skill-builder', description: 'Helps users learn and develop new professional and personal skills with tailored learning paths.', Icon: Wrench },
  { name: 'Essay Evaluator', slug: 'essay-evaluator', description: 'Evaluates written essays and provides detailed feedback on grammar, structure, and argumentation.', Icon: FileCheck },
  { name: 'Adaptive Learning', slug: 'adaptive-learning', description: 'Creates personalized learning paths that adapt to your pace and style.', Icon: GitBranch },
  { name: 'History Narrator', slug: 'history-narrator', description: 'Brings history to life with engaging narratives and detailed explanations of historical events.', Icon: History },
  { name: 'Science Explainer', slug: 'science-explainer', description: 'Explains complex scientific concepts in a clear and understandable way.', Icon: FlaskConical },
  { name: 'Language Translator', slug: 'language-translator', description: 'Provides advanced, context-aware translations between dozens of languages.', Icon: Languages },
  { name: 'Quiz Master', slug: 'quiz-master', description: 'Generates quizzes on any subject to test your knowledge and help you study.', Icon: HelpCircle },
  { name: 'Virtual Classroom', slug: 'virtual-classroom', description: 'Facilitates interactive virtual learning experiences and workshops.', Icon: School },
  { name: 'Curriculum Designer', slug: 'curriculum-designer', description: 'Assists educators in designing comprehensive and effective curricula.', Icon: Library },
  { name: 'Parent Helper', slug: 'parent-helper', description: 'Provides support and resources for parents on child development and education.', Icon: Baby },
  { name: 'Career Counselor', slug: 'career-counselor', description: 'Provides guidance, resume feedback, and mentorship for professional career development.', Icon: UserCog },
  { name: 'Research Assistant', slug: 'research-assistant', description: 'Assists with academic research, from literature reviews to data analysis.', Icon: BookText },
  { name: 'Coding Mentor', slug: 'coding-mentor', description: 'Provides guidance, examples, and debugging help for programming students.', Icon: GitCommit },
  { name: 'Cultural Guide', slug: 'cultural-guide', description: 'Offers insights and information about different cultures, customs, and etiquette.', Icon: Globe2 },
  { name: 'Art History Docent', slug: 'art-history-docent', description: 'Provides guided tours and detailed information about art history and famous artworks.', Icon: Theater },
  { name: 'Math Solver', slug: 'math-solver', description: 'Solves mathematical problems step-by-step, from algebra to calculus.', Icon: Sigma },
  { name: 'Debate Coach', slug: 'debate-coach', description: 'Helps you prepare for debates by structuring arguments and anticipating counter-arguments.', Icon: Group },

  // HealthTech & Wellness
  { name: 'Symptom Checker', slug: 'symptom-checker', description: 'Provides potential causes for medical symptoms for informational purposes.', Icon: Thermometer },
  { name: 'Drug Advisor', slug: 'drug-advisor', description: 'Offers information on pharmaceuticals, including usage, side effects, and interactions.', Icon: Pill },
  { name: 'Mental Health Companion', slug: 'mental-health-companion', description: 'A supportive companion for daily check-ins and promoting mental wellness.', Icon: HeartPulse },
  { name: 'Lab Report Analyzer', slug: 'lab-report-analyzer', description: 'Analyzes and explains medical lab reports in easy-to-understand terms.', Icon: FileHeart },
  { name: 'TeleHealth Assistant', slug: 'telehealth-assistant', description: 'Facilitates remote telehealth consultations by summarizing information and preparing questions.', Icon: MonitorSmartphone },
  { name: 'Medical Scribe', slug: 'medical-scribe', description: 'Automates the process of taking medical notes during patient consultations.', Icon: ClipboardPen },
  { name: 'Nutritionist', slug: 'nutritionist', description: 'Provides personalized nutritional advice, meal planning, and recipe suggestions.', Icon: Sprout },
  { name: 'Fitness Coach', slug: 'fitness-coach', description: 'Creates personalized workout plans and guides users through fitness routines.', Icon: Dumbbell },
  { name: 'Sleep Optimizer', slug: 'sleep-optimizer', description: 'Analyzes sleep patterns and provides recommendations for improving sleep quality.', Icon: Bed },
  { name: 'Stress Reducer', slug: 'stress-reducer', description: 'Offers guided mindfulness exercises, meditation, and techniques to reduce stress.', Icon: Sun },
  { name: 'First Aid Guide', slug: 'first-aid-guide', description: 'Provides immediate, step-by-step first aid instructions for common emergencies.', Icon: Stethoscope },
  { name: 'Wellness Planner', slug: 'wellness-planner', description: 'Helps you create and track a holistic wellness plan for mind and body.', Icon: CalendarDays },
  { name: 'Allergy Tracker', slug: 'allergy-tracker', description: 'Helps track potential allergens in food and environment to identify triggers.', Icon: LeafyGreen },
  { name: 'Elderly Care Support', slug: 'elderly-care-support', description: 'Provides reminders and support for caregivers of the elderly.', Icon: PersonStanding },
  { name: 'Baby Health Guide', slug: 'baby-health-guide', description: 'Offers guidance and information on baby health, milestones, and care.', Icon: Baby },

  // FinTech & E-Commerce Innovations
  { name: 'Expense Tracker', slug: 'expense-tracker', description: 'Tracks and categorizes personal or business expenses automatically from receipts or entries.', Icon: Wallet2 },
  { name: 'Investment Planner', slug: 'investment-planner', description: 'Assists in creating and managing investment portfolios based on risk tolerance and goals.', Icon: LineChart },
  { name: 'Fraud Detector', slug: 'fraud-detector', description: 'Detects and flags potentially fraudulent financial transactions in real-time.', Icon: ShieldAlert },
  { name: 'E-Commerce Optimizer', slug: 'ecommerce-optimizer', description: 'Optimizes e-commerce stores for conversion rates, user experience, and sales performance.', Icon: ShoppingBag },
  { name: 'Budget Advisor', slug: 'budget-advisor', description: 'Helps create and manage personal or household budgets to achieve financial goals.', Icon: Banknote },
  { name: 'Tax Preparer', slug: 'tax-preparer', description: 'Provides assistance with tax preparation and helps identify potential deductions.', Icon: Receipt },
  { name: 'Loan Eligibility', slug: 'loan-eligibility', description: 'Assesses eligibility for various types of loans based on financial data.', Icon: CreditCard },
  { name: 'Personal Finance Guru', slug: 'personal-finance-guru', description: 'Offers holistic personal finance advice, from saving to investing.', Icon: UserCheck },
  { name: 'Market Segmenter', slug: 'market-segmenter', description: 'Analyzes customer data to identify and define key market segments.', Icon: Users2 },
  { name: 'Customer Service Bot', slug: 'customer-service-bot', description: 'Provides automated, 24/7 customer service for your business.', Icon: MessageSquarePlus },
  { name: 'Inventory Manager', slug: 'inventory-manager', description: 'Helps businesses track and manage inventory levels to prevent stockouts and overstocking.', Icon: Package },
  { name: 'Pricing Strategist', slug: 'pricing-strategist', description: 'Develops optimal pricing strategies based on market data, costs, and competitor pricing.', Icon: DollarSign },
  { name: 'Payment Gateway Advisor', slug: 'payment-gateway-advisor', description: 'Recommends the best payment gateway solutions for your e-commerce business.', Icon: KeyRound },
  { name: 'SEO Optimizer', slug: 'seo-optimizer', description: 'Analyzes and optimizes website content for better search engine rankings.', Icon: SearchSlash },
  { name: 'Affiliate Marketer', slug: 'affiliate-marketer', description: 'Helps develop and manage affiliate marketing programs and strategies.', Icon: Handshake },

  // Communication & Social Interaction
  { name: 'WhatsApp Responder', slug: 'whatsapp-responder', description: 'Automates responses and manages conversations on WhatsApp Business accounts.', Icon: MessageCircle },
  { name: 'Community Moderator', slug: 'community-moderator', description: 'Helps moderate online communities, forums, and social media groups to maintain a positive environment.', Icon: Shield },
  { name: 'Dating Coach', slug: 'dating-coach', description: 'Provides advice on creating dating profiles, conversation starters, and relationship tips.', Icon: Star },
  { name: 'Sohbat Companion', slug: 'sohbat-companion', description: 'An AI companion designed for friendly conversation, companionship, and sharing ideas.', Icon: Ear },
  { name: 'Social Media Manager', slug: 'social-media-manager', description: 'Manages social media accounts by creating posts, scheduling content, and analyzing engagement.', Icon: Mail },
  { name: 'Email Assistant', slug: 'email-assistant', description: 'Helps draft, summarize, and manage your email inbox more efficiently.', Icon: Mail },
  { name: 'Meeting Summarizer', slug: 'meeting-summarizer', description: 'Transcribes and summarizes meetings, highlighting key decisions and action items.', Icon: FileClock },
  { name: 'Public Speaker Coach', slug: 'public-speaker-coach', description: 'Helps you practice and improve your public speaking skills, from delivery to content.', Icon: Airplay },
  { name: 'Negotiation Coach', slug: 'negotiation-coach', description: 'Simulates negotiation scenarios and provides strategies for achieving better outcomes.', Icon: HandCoins },
  { name: 'Conflict Resolver', slug: 'conflict-resolver', description: 'Provides neutral, step-by-step guidance for resolving interpersonal conflicts.', Icon: Verified },
  { name: 'Chatbot Designer', slug: 'chatbot-designer', description: 'Designs and builds conversational flows for custom chatbots.', Icon: BotMessageSquare },
  { name: 'Interview Coach', slug: 'interview-coach', description: 'Helps you prepare for job interviews with mock questions and feedback.', Icon: SquareUserRound },
  { name: 'Story Editor', slug: 'story-editor', description: 'Provides editorial feedback on stories, scripts, and other narrative works.', Icon: SquarePen },
  { name: 'Report Writer', slug: 'report-writer', description: 'Generates structured and well-written reports from data and bullet points.', Icon: File },
  { name: 'Biography Builder', slug: 'biography-builder', description: 'Helps write personal or professional biographies for different platforms.', Icon: SquareUser },

  // Global & Innovation Foresight
  { name: 'Trend Forecaster', slug: 'trend-forecaster', description: 'Forecasts emerging trends in technology, culture, and business.', Icon: TrendingUp },
  { name: 'Patent Scout', slug: 'patent-scout', description: 'Scours patent databases to find new and relevant inventions in any industry.', Icon: ScanSearch },
  { name: 'Green Tech Advisor', slug: 'green-tech-advisor', description: 'Advises on green technologies, sustainable practices, and environmental impact.', Icon: Leaf },
  { name: 'Real Estate Command Center', slug: 'real-estate-command-center', description: 'Analyzes real estate markets, property values, and investment opportunities.', Icon: Building },
  { name: 'Geopolitical Analyst', slug: 'geopolitical-analyst', description: 'Analyzes and provides insights on geopolitical events and trends.', Icon: Globe },
  { name: 'Futures Strategist', slug: 'futures-strategist', description: 'Helps organizations develop long-term strategies by analyzing potential future scenarios.', Icon: Telescope },
  { name: 'Innovation Scout', slug: 'innovation-scout', description: 'Scouts for emerging technologies, startups, and innovative ideas across industries.', Icon: Lightbulb },
  { name: 'Disruptor Analyzer', slug: 'disruptor-analyzer', description: 'Analyzes potentially disruptive technologies and business models in your industry.', Icon: Puzzle },
  { name: 'Global Market Entry', slug: 'global-market-entry', description: 'Provides strategies and data for entering new international markets.', Icon: ShipIcon },
  { name: 'Urban Planner', slug: 'urban-planner', description: 'Assists in urban planning, zoning analysis, and architectural design modeling.', Icon: DraftingCompass },

  // Experimental & Metaverse Development
  { name: 'Virtual World Builder', slug: 'virtual-world-builder', description: 'Builds and manages interactive virtual worlds and environments from your descriptions.', Icon: Cuboid },
  { name: 'Avatar Generator', slug: 'avatar-generator', description: 'Generates realistic, stylized, or fantasy user avatars for games and virtual worlds.', Icon: UserRoundCog },
  { name: 'Voice Cloner', slug: 'voice-cloner', description: 'Clones a voice from a short audio sample to be used in various applications (with consent).', Icon: MicVocal },
  { name: 'NFT Creator', slug: 'nft-creator', description: 'Generates artwork and metadata for creating Non-Fungible Tokens (NFTs).', Icon: Wand2 },
  { name: 'VR Experience Generator', slug: 'vr-experience-generator', description: 'Generates scripts and assets for creating virtual reality experiences.', Icon: View },
  { name: 'Hologram Designer', slug: 'hologram-designer', description: 'Designs 3D models and visuals suitable for holographic displays.', Icon: Move },
  { name: 'Digital Twin Manager', slug: 'digital-twin-manager', description: 'Creates and manages digital twins of real-world objects, systems, or processes.', Icon: Combine },

  // Real-World Grounding & Information
  { name: 'Fact-Checker', slug: 'fact-checker', description: 'Verifies and fact-checks information from news articles, social media, and other sources.', Icon: ClipboardCheck },
  { name: 'Local Guide', slug: 'local-guide', description: 'Provides local information, directions, and recommendations for points of interest.', Icon: MapPin },
  { name: 'News Aggregator', slug: 'news-aggregator', description: 'Aggregates and summarizes news from around the world based on your interests.', Icon: Newspaper },
  { name: 'Weather Forecaster', slug: 'weather-forecaster', description: 'Provides current weather conditions and forecasts for any location.', Icon: CloudSun },
  { name: 'Event Finder', slug: 'event-finder', description: 'Finds local events, concerts, and activities based on your interests and location.', Icon: Ticket },
  { name: 'Restaurant Recommender', slug: 'restaurant-recommender', description: 'Recommends restaurants based on cuisine, price, location, and reviews.', Icon: Pizza },
  { name: 'Travel Planner', slug: 'travel-planner', description: 'Helps plan trips by suggesting itineraries, booking flights, and finding accommodations.', Icon: Plane },
  { name: 'Currency Converter', slug: 'currency-converter', description: 'Converts between different currencies using the latest exchange rates.', Icon: Coins },
  { name: 'Time Zone Helper', slug: 'time-zone-helper', description: 'Helps manage time differences across multiple time zones.', Icon: Clock },
  { name: 'Dictionary & Thesaurus', slug: 'dictionary-thesaurus', description: 'Provides definitions, synonyms, antonyms, and etymologies for words.', Icon: BookCopy },
  { name: 'Recipe Finder', slug: 'recipe-finder', description: 'Finds recipes based on ingredients, cuisine, or dietary restrictions.', Icon: Apple },
  { name: 'Product Reviewer', slug: 'product-reviewer', description: 'Summarizes product reviews and provides a consensus on quality and value.', Icon: ShoppingBag },
  { name: 'Celebrity Bio', slug: 'celebrity-bio', description: 'Provides biographical information about famous people.', Icon: CircleUser },
  { name: 'Historical Events Linker', slug: 'historical-events-linker', description: 'Connects historical events, people, and places to show their relationships.', Icon: FolderGit2 },
  { name: 'Sports Stats', slug: 'sports-stats', description: 'Provides statistics, scores, and historical data for various sports and teams.', Icon: Medal },
  { name: 'Movie Info', slug: 'movie-info', description: 'Provides information about movies, including cast, crew, plot summaries, and reviews.', Icon: Film },
  { name: 'Book Summarizer', slug: 'book-summarizer', description: 'Provides concise summaries of popular books.', Icon: BookOpen },
  { name: 'Song Lyrics Finder', slug: 'song-lyrics-finder', description: 'Finds the lyrics for any given song.', Icon: AudioWaveform },
  { name: 'Academic Paper Finder', slug: 'academic-paper-finder', description: 'Searches academic databases to find research papers on specific topics.', Icon: FileQuestion },
  { name: 'Wikipedia Lookup', slug: 'wikipedia-lookup', description: 'Quickly looks up and summarizes information from Wikipedia.', Icon: Globe },

  // Advanced Cognition & Research
  { name: 'Concept Mapper', slug: 'concept-mapper', description: 'Visually maps out complex concepts and their relationships to aid understanding.', Icon: GitGraph },
  { name: 'Theory Proposer', slug: 'theory-proposer', description: 'Proposes new scientific theories or hypotheses based on existing data.', Icon: LightbulbOff },
  { name: 'Paradox Solver', slug: 'paradox-solver', description: 'Analyzes and attempts to resolve logical paradoxes.', Icon: HelpCircle },
  { name: 'Critical Thinker', slug: 'critical-thinker', description: 'Analyzes arguments, identifies logical fallacies, and strengthens reasoning.', Icon: Brain },
  { name: 'Scenario Planner', slug: 'scenario-planner', description: 'Develops and analyzes multiple future scenarios for strategic planning.', Icon: Waypoints },
  { name: 'Data Scientist', slug: 'data-scientist', description: 'Performs complex data analysis, statistical modeling, and machine learning tasks.', Icon: BarChart },
  { name: 'Philosopher', slug: 'philosopher', description: 'Engages in deep philosophical discussions and explores complex ethical questions.', Icon: Drama },
  { name: 'Quantum Computer', slug: 'quantum-computer', description: 'Simulates quantum computing algorithms and principles.', Icon: Atom },
  { name: 'BioTech Innovator', slug: 'biotech-innovator', description: 'Assists in designing biotech experiments and analyzing genetic data.', Icon: Dna },
  { name: 'NeuroLinguist', slug: 'neurolinguist', description: 'Analyzes the relationship between language and the brain.', Icon: BrainCircuit },

  // Media & Content Creation
  { name: 'Blog Post Generator', slug: 'blog-post-generator', description: 'Generates complete, well-structured blog posts on any topic.', Icon: FileText },
  { name: 'Social Post Creator', slug: 'social-post-creator', description: 'Creates engaging posts for various social media platforms.', Icon: ThumbsUp },
  { name: 'Podcast Scripter', slug: 'podcast-scripter', description: 'Writes scripts and talking points for podcast episodes.', Icon: Podcast },
  { name: 'YouTube Idea Generator', slug: 'youtube-idea-generator', description: 'Brainstorms and develops ideas for YouTube videos and series.', Icon: Video },
  { name: 'Infographic Designer', slug: 'infographic-designer', description: 'Designs visually appealing and informative infographics from data.', Icon: LayoutTemplate },
  { name: 'Editorial Assistant', slug: 'editorial-assistant', description: 'Provides editing, proofreading, and style suggestions for written content.', Icon: ClipboardPen },
  { name: 'Headline Generator', slug: 'headline-generator', description: 'Generates catchy and effective headlines for articles and advertisements.', Icon: Sparkles },
  { name: 'Press Release Generator', slug: 'press-release-generator', description: 'Writes professional press releases for company announcements.', Icon: Newspaper },
  { name: 'Brand Storyteller', slug: 'brand-storyteller', description: 'Develops a compelling brand narrative and story.', Icon: BookCopy },
  { name: 'Character Creator', slug: 'character-creator', description: 'Creates detailed and believable characters for stories, games, and scripts.', Icon: User },

  // Environmental & Sustainability
  { name: 'Climate Impact AI', slug: 'climate-impact-ai', description: 'Analyzes and reports on the potential climate impact of various activities.', Icon: SunSnow },
  { name: 'Eco-Policy Advisor', slug: 'eco-policy-advisor', description: 'Advises on the creation and implementation of effective environmental policies.', Icon: File },
  { name: 'Renewable Energy Planner', slug: 'renewable-energy-planner', description: 'Helps plan and model renewable energy projects, like solar and wind farms.', Icon: Wind },
  { name: 'Waste Manager', slug: 'waste-manager', description: 'Provides strategies for waste reduction, recycling, and management.', Icon: Recycle },
  { name: 'Water Resource AI', slug: 'water-resource-ai', description: 'Analyzes and manages water resources for sustainability.', Icon: Droplets },
  { name: 'Biodiversity Monitor', slug: 'biodiversity-monitor', description: 'Monitors and reports on biodiversity in specific ecosystems.', Icon: Bird },
  { name: 'Pollution Tracker', slug: 'pollution-tracker', description: 'Tracks air, water, and soil pollution levels from various data sources.', Icon: Heater },
  { name: 'Sustainable Agriculture AI', slug: 'sustainable-agriculture-ai', description: 'Provides advice on sustainable farming and agricultural practices.', Icon: Wheat },
  { name: 'Carbon Footprint Calculator', slug: 'carbon-footprint-calculator', description: 'Calculates the carbon footprint of individuals, products, or organizations.', Icon: CloudCog },
  { name: 'Disaster Predictor', slug: 'disaster-predictor', description: 'Predicts and helps mitigate the impact of natural disasters using historical and real-time data.', Icon: Tornado },

  // Personal Productivity & Lifestyle
  { name: 'Task Manager', slug: 'task-manager', description: 'Helps you organize, prioritize, and manage your daily tasks and to-do lists.', Icon: ClipboardCheck },
  { name: 'Time Optimizer', slug: 'time-optimizer', description: 'Analyzes your schedule and suggests ways to optimize your time for maximum productivity.', Icon: Clock },
  { name: 'Habit Builder', slug: 'habit-builder', description: 'Helps you build positive habits and break negative ones with reminders and tracking.', Icon: Repeat },
  { name: 'Goal Setter', slug: 'goal-setter', description: 'Assists in setting, tracking, and achieving your personal and professional goals.', Icon: Flag },
  { name: 'Mindfulness Coach', slug: 'mindfulness-coach', description: 'Guides you through mindfulness exercises and meditation to improve focus and well-being.', Icon: Heart },
  { name: 'Personal Shopper', slug: 'personal-shopper', description: 'Finds and recommends products based on your style, preferences, and budget.', Icon: ShoppingBag },
  { name: 'Fashion Advisor', slug: 'fashion-advisor', description: 'Provides fashion advice, style recommendations, and outfit suggestions.', Icon: Shirt },
  { name: 'Home Organizer', slug: 'home-organizer', description: 'Helps you declutter and organize your home with practical tips and plans.', Icon: Home },
  { name: 'Pet Care Advisor', slug: 'pet-care-advisor', description: 'Provides advice on pet health, nutrition, and care.', Icon: PawPrint },
  { name: 'Hobby Finder', slug: 'hobby-finder', description: 'Suggests new hobbies and interests based on your personality and preferences.', Icon: Gamepad },

  // Creative Arts & Entertainment
  { name: 'Poetry Composer', slug: 'poetry-composer', description: 'Composes poetry in various styles and forms, from sonnets to free verse.', Icon: Feather },
  { name: 'Song Writer', slug: 'song-writer', description: 'Helps write lyrics and compose melodies for original songs.', Icon: Music },
  { name: 'Novel Plot Generator', slug: 'novel-plot-generator', description: 'Generates detailed plot outlines and story structures for novels.', Icon: BookOpen },
  { name: 'Comic Book Artist', slug: 'comic-book-artist', description: 'Helps create comic book layouts, character designs, and storyboards.', Icon: Brush },
  { name: 'Short Story Writer', slug: 'short-story-writer', description: 'Writes complete short stories based on your prompts and ideas.', Icon: BookCopy },
  { name: 'Playwright', slug: 'playwright', description: 'Assists in writing scripts, dialogue, and stage directions for plays.', Icon: Theater },
  { name: 'Material Science AI', slug: 'material-science-ai', description: 'Analyzes and predicts the properties of new materials.', Icon: Cuboid },
  { name: 'Physics Simulator', slug: 'physics-simulator', description: 'Simulates physical systems and experiments.', Icon: TestTube },
  { name: 'Chemical Synthesizer', slug: 'chemical-synthesizer', description: 'Designs synthesis pathways for chemical compounds.', Icon: FlaskConical },
  { name: 'Astronomy Guide', slug: 'astronomy-guide', description: 'Provides information about celestial objects, constellations, and astronomical events.', Icon: Telescope },
  { name: 'Robotics Designer', slug: 'robotics-designer', description: 'Designs robotic systems and simulates their behavior.', Icon: Bot },
  { name: 'Genetics Analyzer', slug: 'genetics-analyzer', description: 'Analyzes genetic data to identify traits and potential health risks.', Icon: Dna },
  { name: 'Fluid Dynamics AI', slug: 'fluid-dynamics-ai', description: 'Simulates and analyzes fluid dynamics for engineering and scientific applications.', Icon: Waves },
  { name: 'Geology Expert', slug: 'geology-expert', description: 'Provides expertise on geological formations, minerals, and earth processes.', Icon: MountainSnow },
  { name: 'Nanotech Innovator', slug: 'nanotech-innovator', description: 'Designs and simulates nanoscale devices and materials.', Icon: Microscope },
  { name: 'Energy Engineer', slug: 'energy-engineer', description: 'Helps design and optimize energy systems, from power plants to renewable grids.', Icon: Zap },

  // Travel & Hospitality
  { name: 'Hotel Recommender', slug: 'hotel-recommender', description: 'Recommends hotels based on price, location, amenities, and user reviews.', Icon: Hotel },
  { name: 'Flight Finder', slug: 'flight-finder', description: 'Finds the best flight options based on your destination, dates, and budget.', Icon: Plane },
  { name: 'Visa Guide', slug: 'visa-guide', description: 'Provides information on visa requirements and application processes for different countries.', Icon: CreditCard },
  { name: 'Packing Assistant', slug: 'packing-assistant', description: 'Creates a personalized packing list for your trip based on destination and activities.', Icon: Briefcase },
  { name: 'Local Event Planner', slug: 'local-event-planner', description: 'Finds and helps you plan attendance at local events, festivals, and concerts.', Icon: CalendarDays },
  { name: 'Cultural Interpreter', slug: 'cultural-interpreter', description: 'Provides real-time interpretation of cultural norms, etiquette, and basic phrases.', Icon: Languages },
  { name: 'Budget Traveler', slug: 'budget-traveler', description: 'Helps you plan trips on a tight budget by finding deals and free activities.', Icon: HandCoins },
  { name: 'Adventure Planner', slug: 'adventure-planner', description: 'Plans adventurous trips, from hiking and camping to extreme sports.', Icon: Mountain },
  { name: 'Dining Guide', slug: 'dining-guide', description: 'Provides recommendations for local dining experiences, from street food to fine dining.', Icon: Utensils },
  { name: 'Tourism Promoter', slug: 'tourism-promoter', description: 'Helps promote local tourist destinations and attractions.', Icon: Map },

  // Legal & Policy Analysis
  { name: 'Contract Analyzer', slug: 'contract-analyzer', description: 'Analyzes legal contracts to identify key clauses, risks, and obligations.', Icon: FileSignature },
  { name: 'Policy Drafter', slug: 'policy-drafter', description: 'Assists in drafting clear, effective, and enforceable policies and regulations.', Icon: FilePen },
  { name: 'Regulatory Compliance', slug: 'regulatory-compliance', description: 'Checks projects and documents for compliance with relevant laws and regulations.', Icon: ShieldCheck },
  { name: 'Legal Researcher', slug: 'legal-researcher', description: 'Conducts legal research, citing relevant case law and statutes.', Icon: BookCopy },
  { name: 'Intellectual Property', slug: 'intellectual-property', description: 'Provides information and guidance on patents, trademarks, and copyrights.', Icon: BrainCircuit },
  { name: 'Arbitration Mediator', slug: 'arbitration-mediator', description: 'Acts as a neutral mediator in arbitrating disputes.', Icon: Handshake },
  { name: 'Human Rights Monitor', slug: 'human-rights-monitor', description: 'Monitors and reports on human rights issues based on public data.', Icon: UserCheck },
  { name: 'Ethics Review Board', slug: 'ethics-review-board', description: 'Simulates an ethics review for projects, research, and business proposals.', Icon: ShieldQuestion },
  { name: 'Civil Rights Advocate', slug: 'civil-rights-advocate', description: 'Provides information and resources related to civil rights and liberties.', Icon: Landmark },
  { name: 'International Law Advisor', slug: 'international-law-advisor', description: 'Provides guidance on international law, treaties, and conventions.', Icon: Globe2 },
];
