import type { LucideIcon } from 'lucide-react';
import { Leaf, Video, Network, BrainCircuit, Eye, Mic, Languages, Combine, Shield, Scale, Box, DollarSign, TrendingUp, Search, Cog, Target, ClipboardCheck, Cloud, ShieldCheck, Banknote, Users, Truck, Landmark, HeartHandshake, Siren, AreaChart, Scan, FileScan, Building2, Receipt, Vote, Code, PenTool, Plug, TestTube2, Rocket, Paintbrush, Clapperboard, Music, Cuboid, MicVocal, Book, Megaphone, Podcast, AudioWaveform, Film, GraduationCap, BookOpen, MessageSquare, Wrench, ClipboardPen, FileCheck, GitBranch, HelpCircle, School, BookText, Thermometer, Pill, Smile, CalendarDays, FileCode, FileHeart, Activity, MonitorSmartphone, FileText, FlaskConical, Wallet, LineChart, ShieldAlert, Bot, MessageCircle, Users2, Star, Sun, Dumbbell, Sprout, Telescope, Microscope, Globe, Blocks, Brick, Home, View, Move, DraftingCompass, Drama, Hand, Gavel, Briefcase, LandPlot, Ear } from 'lucide-react';

export type Agent = {
  name: string;
  description: string;
  Icon: LucideIcon;
};

export const agents: Agent[] = [
  {
    name: 'PlantDiagnoser',
    description: 'An expert botanist specializing in diagnosing plant illnesses.',
    Icon: Leaf,
  },
  {
    name: 'VideoGenerator',
    description: 'An AI that can generate videos from text or image prompts.',
    Icon: Video,
  },
  {
    name: 'AfgCore Orchestrator',
    description: 'Manages agent lifecycle, scaling, and routing.',
    Icon: Network,
  },
  {
    name: 'AfgMemory Engine',
    description: 'Manages user context and cross-agent insights.',
    Icon: BrainCircuit,
  },
  {
    name: 'AfgVision Agent',
    description: 'Image/video understanding.',
    Icon: Eye,
  },
  {
    name: 'AfgVoice Agent',
    description: 'Real-time speech-to-text pipeline.',
    Icon: Mic,
  },
  {
    name: 'AfgLang Router',
    description: '60+ language translation & adaptation.',
    Icon: Languages,
  },
  {
    name: 'AfgData Fusion',
    description: 'Creates knowledge graphs from multi-modal data.',
    Icon: Combine,
  },
  {
    name: 'AfgSecurity Guardian',
    description: 'Zero-trust AI monitor and access control.',
    Icon: Shield,
  },
  {
    name: 'AfgEthics Core',
    description: 'Bias detection, audit, and AI compliance.',
    Icon: Scale,
  },
  {
    name: 'AfgMLOps Manager',
    description: 'Automates Vertex AI pipeline deployment.',
    Icon: Box,
  },
  {
    name: 'AfgCost Optimizer',
    description: 'Real-time spend balancer.',
    Icon: DollarSign,
  },
  { name: 'BizStrategy AI', description: 'Business strategy formulation.', Icon: TrendingUp },
  { name: 'MarketIntel AI', description: 'Market intelligence and analysis.', Icon: Search },
  { name: 'ProcessOptimizer AI', description: 'Business process optimization.', Icon: Cog },
  { name: 'ROI Predictor AI', description: 'Predicts return on investment.', Icon: Target },
  { name: 'Compliance Auditor AI', description: 'Audits for compliance.', Icon: ClipboardCheck },
  { name: 'CloudOps Advisor AI', description: 'Advises on cloud operations.', Icon: Cloud },
  { name: 'CyberDefense AI', description: 'Cyber defense strategies.', Icon: ShieldCheck },
  { name: 'FinOps AI', description: 'Financial operations optimization.', Icon: Banknote },
  { name: 'TalentMatch AI', description: 'Matches talent with opportunities.', Icon: Users },
  { name: 'SupplyChain Predictor AI', description: 'Predicts supply chain disruptions.', Icon: Truck },
  { name: 'E-Gov Automation AI', description: 'Automates e-governance processes.', Icon: Landmark },
  { name: 'Citizen Support AI', description: 'Provides support to citizens.', Icon: HeartHandshake },
  { name: 'Policy Simulator AI', description: 'Simulates policy outcomes.', Icon: Scale },
  { name: 'Disaster Response AI', description: 'Aids in disaster response.', Icon: Siren },
  { name: 'Population Insights AI', description: 'Provides population insights.', Icon: AreaChart },
  { name: 'Corruption Detector AI', description: 'Detects corruption.', Icon: Scan },
  { name: 'Document Digitizer AI', description: 'Digitizes documents.',
  Icon: FileScan },
  { name: 'SmartCity Planner AI', description: 'Plans smart city infrastructure.', Icon: Building2 },
  { name: 'Tax Assistant AI', description: 'Assists with tax-related queries.', Icon: Receipt },
  { name: 'Election Intel AI', description: 'Provides election intelligence.', Icon: Vote },
  { name: 'CodeGen AI (TypeScript/Node)', description: 'Generates TypeScript/Node code.', Icon: Code },
  { name: 'UI/UX Designer AI (Figma→Next.js)', description: 'Designs UI/UX from Figma to Next.js.', Icon: PenTool },
  { name: 'API Builder AI (OpenAPI→Cloud Run)', description: 'Builds APIs from OpenAPI to Cloud Run.', Icon: Plug },
  { name: 'TestSuite AI (Unit + Integration)', description: 'Generates test suites.', Icon: TestTube2 },
  { name: 'Deployment AI (CI/CD Vertex Hook)', description: 'Automates deployment.', Icon: Rocket },
  { name: 'LogoGen AI', description: 'Generates logos.', Icon: Paintbrush },
  { name: 'Video Director AI', description: 'Directs video production.', Icon: Clapperboard },
  { name: 'Music Composer AI', description: 'Composes music.', Icon: Music },
  { name: '3D Asset AI', description: 'Generates 3D assets.', Icon: Cuboid },
  { name: 'BrandVoice AI', description: 'Develops brand voice.', Icon: MicVocal },
  { name: 'Script Writer AI', description: 'Writes scripts.', Icon: Book },
  { name: 'AdCampaign AI', description: 'Manages ad campaigns.', Icon: Megaphone },
  { name: 'StoryTeller AI', description: 'Tells stories.', Icon: Film },
  { name: 'Video Podcast Studio AI', description: 'Produces video podcasts.', Icon: Podcast },
  { name: 'Music Production Studio AI', description: 'Produces music.', Icon: AudioWaveform },
  { name: 'Kankor Tutor AI', description: 'Kankor exam tutoring.', Icon: GraduationCap },
  { name: 'Quran Tutor AI', description: 'Quranic studies tutor.', Icon: BookOpen },
  { name: 'English Coach AI', description: 'Coaches English language skills.', Icon: MessageSquare },
  { name: 'Language Lab AI', description: 'Language learning laboratory.', Icon: Languages },
  { name: 'SkillBuilder AI', description: 'Builds new skills.', Icon: Wrench },
  { name: 'ExamPrep AI', description: 'Prepares for exams.', Icon: ClipboardPen },
  { name: 'EssayEvaluator AI', description: 'Evaluates essays.', Icon: FileCheck },
  { name: 'AdaptiveLearning AI', description: 'Adapts to learning styles.', Icon: GitBranch },
  { name: 'QuizMaster AI', description: 'Generates quizzes.', Icon: HelpCircle },
  { name: 'VirtualClassroom AI', description: 'Manages virtual classrooms.', Icon: School },
  { name: 'Research Summarizer AI', description: 'Summarizes research papers.', Icon: BookText },
  { name: 'SymptomChecker AI', description: 'Checks medical symptoms.', Icon: Thermometer },
  { name: 'DrugAdvisor AI', description: 'Advises on drugs.', Icon: Pill },
  { name: 'MentalHealth AI Companion', description: 'A mental health companion.', Icon: Smile },
  { name: 'Appointment AI', description: 'Manages appointments.', Icon: CalendarDays },
  { name: 'MedicalCoding AI', description: 'Assists with medical coding.', Icon: FileCode },
  { name: 'Insurance Claim AI', description: 'Processes insurance claims.', Icon: FileHeart },
  { name: 'Disease Predictor AI', description: 'Predicts diseases.', Icon: Activity },
  { name: 'TeleHealth AI', description: 'Provides telehealth services.', Icon: MonitorSmartphone },
  { name: 'Patient Record AI', description: 'Manages patient records.', Icon: FileText },
  { name: 'LabReport Analyzer AI', description: 'Analyzes lab reports.', Icon: FlaskConical },
  { name: 'Expense Tracker AI', description: 'Tracks expenses.', Icon: Wallet },
  { name: 'Investment Planner AI', description: 'Plans investments.', Icon: LineChart },
  { name: 'Credit Score AI', description: 'Analyzes credit scores.', Icon: Target },
  { name: 'Fraud Detector AI', description: 'Detects financial fraud.', Icon: ShieldAlert },
  { name: 'Crypto Market AI', description: 'Analyzes crypto markets.', Icon: DollarSign },
  { name: 'SME Loan AI', description: 'Assists with SME loans.', Icon: Landmark },
  { name: 'Payroll AI', description: 'Manages payroll.', Icon: Banknote },
  { name: 'Accounting AI', description: 'Handles accounting tasks.', Icon: Receipt },
  { name: 'E-Commerce Optimizer AI', description: 'Optimizes e-commerce operations.', Icon: Cog },
  { name: 'FinTech Intelligence AI', description: 'Provides FinTech intelligence.', Icon: Search },
  { name: 'WhatsApp Responder AI', description: 'Responds to WhatsApp messages.', Icon: Bot },
  { name: 'Telegram Bot AI', description: 'A Telegram bot.', Icon: MessageCircle },
  { name: 'Support Desk AI', description: 'Manages support desks.', Icon: Users2 },
  { name: 'Community Moderator AI', description: 'Moderates online communities.', Icon: Shield },
  { name: 'Sentiment Tracker AI', description: 'Tracks sentiment.', Icon: Smile },
  { name: 'Dating Coach & Profile AI', description: 'Coaches dating and profiles.', Icon: Star },
  { name: 'SocialInsights AI', description: 'Provides social media insights.', Icon: Sun },
  { name: 'Content Empire Builder AI', description: 'Builds content empires.', Icon: BookOpen },
  { name: 'Personal Trainer AI', description: 'A personal trainer.', Icon: Dumbbell },
  { name: 'Nutritionist AI', description: 'A nutritionist.', Icon: Sprout },
  { name: 'Trend Forecaster AI', description: 'Forecasts trends.', Icon: TrendingUp },
  { name: 'Patent Scout AI', description: 'Scouts for patents.', Icon: Search },
  { name: 'Quantum Simulator AI', description: 'Simulates quantum mechanics.', Icon: Cuboid },
  { name: 'Genomic Analyzer AI', description: 'Analyzes genomic data.', Icon: Microscope },
  { name: 'Green Tech AI', description: 'Advises on green technology.', Icon: Leaf },
  { name: 'Robotics Control AI', description: 'Controls robotics.', Icon: Bot },
  { name: 'AfgHub Regional AI', description: 'Regional AI hub.', Icon: Globe },
  { name: 'Global Orchestrator AI', description: 'Orchestrates global operations.', Icon: Network },
  { name: 'Localization AI', description: 'Localizes content.', Icon: Languages },
  { name: 'Partner Ecosystem AI', description: 'Manages partner ecosystems.', Icon: Blocks },
  { name: 'Real Estate Command Center AI', description: 'A real estate command center.', Icon: Home },
  { name: 'Virtual World AI', description: 'Builds and manages virtual worlds.', Icon: Blocks },
  { name: 'Avatar Gen AI', description: 'Generates realistic avatars.', Icon: Users2 },
  { name: 'Voice Clone AI', description: 'Clones voices with high fidelity.', Icon: MicVocal },
  { name: 'Motion Capture AI', description: 'Captures and analyzes motion data.', Icon: Move },
  { name: 'Immersive Trainer AI', description: 'Creates immersive training simulations.', Icon: View },
  { name: 'AR Architect AI', description: 'Designs augmented reality experiences.', Icon: DraftingCompass },
  { name: 'VR Event AI', description: 'Organizes and hosts virtual reality events.', Icon: Drama },
  { name: 'Holo Chat AI', description: 'Enables holographic communication.', Icon: MessageCircle },
  { name: 'Emotion Synthesis AI', description: 'Synthesizes realistic emotions in avatars.', Icon: Hand },
  { name: 'Consciousness Simulator AI', description: 'Simulates aspects of consciousness.', Icon: BrainCircuit },
  { name: 'Legal Intelligence AI', description: 'Provides legal insights and research.', Icon: Gavel },
  { name: 'Financial Advisor AI (Personal)', description: 'Offers personalized financial advice.', Icon: Briefcase },
  { name: 'Music & Podcast Production AI', description: 'Automates music and podcast production.', Icon: AudioWaveform },
];